Document: lemonpos-fast
Title: Debian lemonpos-fast Manual
Author: <insert document author here>
Abstract: This manual describes what lemonpos-fast is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lemonpos-fast/lemonpos-fast.sgml.gz

Format: postscript
Files: /usr/share/doc/lemonpos-fast/lemonpos-fast.ps.gz

Format: text
Files: /usr/share/doc/lemonpos-fast/lemonpos-fast.text.gz

Format: HTML
Index: /usr/share/doc/lemonpos-fast/html/index.html
Files: /usr/share/doc/lemonpos-fast/html/*.html
